name = "insightrun-landing"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Cloudflare Workers configuration
main = ".open-next/worker.js"
assets = { directory = ".open-next/assets", binding = "ASSETS" }
