//
//  HistoricalSummary.swift
//  InsightRun
//
//  Model representing a comprehensive historical analysis of all workouts
//  Used for the One-Time Deep Analysis strategy to optimize AI context
//

import Foundation

struct HistoricalSummary: Codable {
    /// The comprehensive summary text generated by AI
    let summary: String

    /// When this summary was generated
    let generatedDate: Date

    /// When this summary was last indexed (for refresh tracking)
    let indexedAt: Date

    /// Schema version for future migrations
    let version: Int

    /// Number of workouts that were analyzed
    let workoutCount: Int

    /// Date range of the workouts analyzed
    let dateRangeStart: Date
    let dateRangeEnd: Date

    /// Check if the summary needs to be refreshed (older than 3 months from indexedAt)
    var needsRefresh: Bool {
        let threeMonthsAgo = Calendar.current.date(byAdding: .month, value: -3, to: Date()) ?? Date()
        return indexedAt < threeMonthsAgo
    }

    /// Days since the summary was generated
    var daysSinceGeneration: Int {
        let calendar = Calendar.current
        let components = calendar.dateComponents([.day], from: generatedDate, to: Date())
        return components.day ?? 0
    }

    /// Human-readable generated date
    nonisolated var generatedDateFormatted: String {
        let formatter = DateFormatter()
        formatter.dateStyle = .medium
        formatter.timeStyle = .short
        return formatter.string(from: generatedDate)
    }

    /// Date range formatted
    nonisolated var dateRangeFormatted: String {
        let formatter = DateFormatter()
        formatter.dateStyle = .short
        let start = formatter.string(from: dateRangeStart)
        let end = formatter.string(from: dateRangeEnd)
        return "\(start) - \(end)"
    }
}

// MARK: - Convenience Initializer

extension HistoricalSummary {
    /// Create a historical summary from an API response
    init(summary: String, workoutCount: Int, dateRangeStart: Date, dateRangeEnd: Date) {
        let now = Date()
        self.summary = summary
        self.generatedDate = now
        self.indexedAt = now
        self.version = 1
        self.workoutCount = workoutCount
        self.dateRangeStart = dateRangeStart
        self.dateRangeEnd = dateRangeEnd
    }
}
