//
//  TrainingPlan.swift
//  InsightRun
//
//  Model for multi-week training plans generated by AI coach
//

import Foundation
import SwiftUI

// MARK: - Training Plan

struct TrainingPlan: Identifiable, Codable {
    let id: UUID
    let name: String
    let goal: String
    let level: FitnessLevel
    var weeks: [TrainingWeek]
    let createdAt: Date
    let startDate: Date?
    let isActive: Bool

    init(
        id: UUID = UUID(),
        name: String,
        goal: String,
        level: FitnessLevel,
        weeks: [TrainingWeek],
        createdAt: Date = Date(),
        startDate: Date? = nil,
        isActive: Bool = false
    ) {
        self.id = id
        self.name = name
        self.goal = goal
        self.level = level
        self.weeks = weeks
        self.createdAt = createdAt
        self.startDate = startDate
        self.isActive = isActive
    }

    var lastAdaptationDate: Date?
    var adaptationAssessment: String?

    var totalWeeks: Int {
        weeks.count
    }

    var totalWorkouts: Int {
        weeks.flatMap { $0.days }.filter { $0.workout != nil }.count
    }

    var isCompleted: Bool {
        let workoutDays = weeks.flatMap { $0.days }.filter { $0.workout != nil }
        return !workoutDays.isEmpty && workoutDays.allSatisfy { $0.isCompleted }
    }

    var currentWeekIndex: Int? {
        guard let start = startDate else { return nil }
        let daysSinceStart = Calendar.current.dateComponents([.day], from: start, to: Date()).day ?? 0
        let weekIndex = daysSinceStart / 7
        return weekIndex < weeks.count ? weekIndex : nil
    }
}

// MARK: - Training Week

struct TrainingWeek: Identifiable, Codable {
    let id: UUID
    let weekNumber: Int
    let phase: TrainingPhase
    var days: [TrainingDay]
    let weeklyVolume: Double? // Total distance in km
    let notes: String?

    init(
        id: UUID = UUID(),
        weekNumber: Int,
        phase: TrainingPhase,
        days: [TrainingDay],
        weeklyVolume: Double? = nil,
        notes: String? = nil
    ) {
        self.id = id
        self.weekNumber = weekNumber
        self.phase = phase
        self.days = days
        self.weeklyVolume = weeklyVolume
        self.notes = notes
    }

    var workoutCount: Int {
        days.filter { $0.workout != nil }.count
    }

    var restDayCount: Int {
        days.filter { $0.isRestDay }.count
    }
}

// MARK: - Training Day

struct TrainingDay: Identifiable, Codable {
    let id: UUID
    let dayOfWeek: DayOfWeek
    let workout: PlannedWorkout?
    var isRestDay: Bool { workout == nil }
    var isCompleted: Bool
    var completedWorkoutId: String? // Link to actual HKWorkout

    private enum CodingKeys: String, CodingKey {
        case id, dayOfWeek, workout, isCompleted, completedWorkoutId
    }

    init(
        id: UUID = UUID(),
        dayOfWeek: DayOfWeek,
        workout: PlannedWorkout? = nil,
        isCompleted: Bool = false,
        completedWorkoutId: String? = nil
    ) {
        self.id = id
        self.dayOfWeek = dayOfWeek
        self.workout = workout
        self.isCompleted = isCompleted
        self.completedWorkoutId = completedWorkoutId
    }
}

// MARK: - Planned Workout

struct PlannedWorkout: Identifiable, Codable {
    let id: UUID
    let type: WorkoutType
    let name: String
    let description: String
    let targetDuration: TimeInterval? // in seconds
    let targetDistance: Double? // in meters
    let targetPace: String? // e.g., "5:30/km"
    let steps: [PlannedWorkoutStep]
    let intensity: WorkoutIntensity

    init(
        id: UUID = UUID(),
        type: WorkoutType,
        name: String,
        description: String,
        targetDuration: TimeInterval? = nil,
        targetDistance: Double? = nil,
        targetPace: String? = nil,
        steps: [PlannedWorkoutStep] = [],
        intensity: WorkoutIntensity = .moderate
    ) {
        self.id = id
        self.type = type
        self.name = name
        self.description = description
        self.targetDuration = targetDuration
        self.targetDistance = targetDistance
        self.targetPace = targetPace
        self.steps = steps
        self.intensity = intensity
    }

    var formattedDuration: String {
        guard let duration = targetDuration else { return "" }
        let minutes = Int(duration) / 60
        if minutes < 60 {
            return "\(minutes) min"
        }
        let hours = minutes / 60
        let remainingMinutes = minutes % 60
        return "\(hours)h \(remainingMinutes)min"
    }

    var formattedDistance: String {
        guard let distance = targetDistance else { return "" }
        return String(format: "%.1f km", distance / 1000)
    }
}

// MARK: - Planned Workout Step

struct PlannedWorkoutStep: Identifiable, Codable {
    let id: UUID
    let type: PlannedStepType
    let duration: TimeInterval? // in seconds
    let distance: Double? // in meters
    let targetPace: String?
    let description: String

    init(
        id: UUID = UUID(),
        type: PlannedStepType,
        duration: TimeInterval? = nil,
        distance: Double? = nil,
        targetPace: String? = nil,
        description: String
    ) {
        self.id = id
        self.type = type
        self.duration = duration
        self.distance = distance
        self.targetPace = targetPace
        self.description = description
    }
}

// MARK: - Enums

enum FitnessLevel: String, Codable, CaseIterable {
    case beginner
    case intermediate
    case advanced

    var displayName: String {
        switch self {
        case .beginner:
            return String(localized: "Beginner", comment: "Fitness level - beginner")
        case .intermediate:
            return String(localized: "Intermediate", comment: "Fitness level - intermediate")
        case .advanced:
            return String(localized: "Advanced", comment: "Fitness level - advanced")
        }
    }
}

enum TrainingPhase: String, Codable, CaseIterable {
    case base
    case build
    case peak
    case taper
    case recovery

    var displayName: String {
        switch self {
        case .base:
            return String(localized: "Base Building", comment: "Training phase - base")
        case .build:
            return String(localized: "Build Phase", comment: "Training phase - build")
        case .peak:
            return String(localized: "Peak Phase", comment: "Training phase - peak")
        case .taper:
            return String(localized: "Taper", comment: "Training phase - taper")
        case .recovery:
            return String(localized: "Recovery", comment: "Training phase - recovery")
        }
    }

    var themeColor: Color {
        switch self {
        case .base: return .blue
        case .build: return .orange
        case .peak: return .red
        case .taper: return .green
        case .recovery: return .purple
        }
    }

    var description: String {
        switch self {
        case .base:
            return String(localized: "Building aerobic base with easy runs", comment: "Training phase description - base")
        case .build:
            return String(localized: "Increasing volume and introducing tempo work", comment: "Training phase description - build")
        case .peak:
            return String(localized: "Race-specific workouts and peak fitness", comment: "Training phase description - peak")
        case .taper:
            return String(localized: "Reducing volume while maintaining intensity", comment: "Training phase description - taper")
        case .recovery:
            return String(localized: "Rest and recovery after race or hard block", comment: "Training phase description - recovery")
        }
    }
}

enum WorkoutType: String, Codable, CaseIterable {
    case easyRun = "easy_run"
    case tempo
    case intervals
    case longRun = "long_run"
    case recovery
    case hillRepeats = "hill_repeats"
    case fartlek
    case crossTraining = "cross_training"

    var displayName: String {
        switch self {
        case .easyRun:
            return String(localized: "Easy Run", comment: "Workout type - easy run")
        case .tempo:
            return String(localized: "Tempo Run", comment: "Workout type - tempo")
        case .intervals:
            return String(localized: "Intervals", comment: "Workout type - intervals")
        case .longRun:
            return String(localized: "Long Run", comment: "Workout type - long run")
        case .recovery:
            return String(localized: "Recovery Run", comment: "Workout type - recovery")
        case .hillRepeats:
            return String(localized: "Hill Repeats", comment: "Workout type - hill repeats")
        case .fartlek:
            return String(localized: "Fartlek", comment: "Workout type - fartlek")
        case .crossTraining:
            return String(localized: "Cross Training", comment: "Workout type - cross training")
        }
    }

    var icon: String {
        switch self {
        case .easyRun: return "figure.walk"
        case .tempo: return "speedometer"
        case .intervals: return "timer"
        case .longRun: return "arrow.right.circle"
        case .recovery: return "bed.double"
        case .hillRepeats: return "arrow.up.right"
        case .fartlek: return "shuffle"
        case .crossTraining: return "bicycle"
        }
    }
}

enum WorkoutIntensity: String, Codable, CaseIterable {
    case easy
    case moderate
    case hard
    case veryHard = "very_hard"

    var displayName: String {
        switch self {
        case .easy:
            return String(localized: "Easy", comment: "Workout intensity - easy")
        case .moderate:
            return String(localized: "Moderate", comment: "Workout intensity - moderate")
        case .hard:
            return String(localized: "Hard", comment: "Workout intensity - hard")
        case .veryHard:
            return String(localized: "Very Hard", comment: "Workout intensity - very hard")
        }
    }

    var color: String {
        switch self {
        case .easy: return "green"
        case .moderate: return "yellow"
        case .hard: return "orange"
        case .veryHard: return "red"
        }
    }

    var themeColor: Color {
        switch self {
        case .easy: return .green
        case .moderate: return .orange
        case .hard: return .orange
        case .veryHard: return .red
        }
    }
}

enum PlannedStepType: String, Codable, CaseIterable {
    case warmup
    case work
    case recovery
    case cooldown
    case interval
    case rest

    var displayName: String {
        switch self {
        case .warmup:
            return String(localized: "Warmup", comment: "Workout step - warmup")
        case .work:
            return String(localized: "Work", comment: "Workout step - work")
        case .recovery:
            return String(localized: "Recovery", comment: "Workout step - recovery")
        case .cooldown:
            return String(localized: "Cooldown", comment: "Workout step - cooldown")
        case .interval:
            return String(localized: "Interval", comment: "Workout step - interval")
        case .rest:
            return String(localized: "Rest", comment: "Workout step - rest")
        }
    }

    var themeColor: Color {
        switch self {
        case .warmup: return .blue
        case .work: return .orange
        case .recovery: return .green
        case .cooldown: return .cyan
        case .interval: return .red
        case .rest: return .gray
        }
    }
}

enum DayOfWeek: Int, Codable, CaseIterable {
    case sunday = 1
    case monday = 2
    case tuesday = 3
    case wednesday = 4
    case thursday = 5
    case friday = 6
    case saturday = 7

    var shortName: String {
        let formatter = DateFormatter()
        formatter.locale = Locale.current
        return formatter.shortWeekdaySymbols[self.rawValue - 1]
    }

    var fullName: String {
        let formatter = DateFormatter()
        formatter.locale = Locale.current
        return formatter.weekdaySymbols[self.rawValue - 1]
    }
}
